In [20]:
import numpy as np

W = 4
H = 4

Q = np.zeros((W*2, H), dtype=float)
K = np.zeros((W*2, H), dtype=float)
V = np.zeros((W*2, H), dtype=float)

for i in range(W*2):
    for j in range(H):
        Q[i, j] = i*H + j + 1
        K[i, j] = i*H + j + 2
        V[i, j] = i*H + j

print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

Q:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]
K:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]
 [26. 27. 28. 29.]
 [30. 31. 32. 33.]]
V:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]


In [21]:
import math

def Attention_Core(Q, K, V, scale=3):
    diff=abs(np.sum(Q-K))
    S=math.e**(-scale*diff)

    print("S: ",S)

    Z=S*V
    print("Z: ",Z)
    print("--------------------------------------")

    return np.array(S,dtype=float),np.array(Z,dtype=float)


In [22]:
S = np.zeros((W*2), dtype=float)
Z = np.zeros((W*2, H), dtype=float)

for i in range(W*2):
    S[i],Z[i]=Attention_Core(Q[i], K[i], V[i])

S:  6.144212353328214e-06
Z:  [0.000000e+00 6.144212e-06 1.228842e-05 1.843264e-05]
--------------------------------------
S:  6.144212353328214e-06
Z:  [2.457685e-05 3.072106e-05 3.686527e-05 4.300949e-05]
--------------------------------------
S:  6.144212353328214e-06
Z:  [4.915370e-05 5.529791e-05 6.144212e-05 6.758634e-05]
--------------------------------------
S:  6.144212353328214e-06
Z:  [7.373055e-05 7.987476e-05 8.601897e-05 9.216319e-05]
--------------------------------------
S:  6.144212353328214e-06
Z:  [9.830740e-05 1.044516e-04 1.105958e-04 1.167400e-04]
--------------------------------------
S:  6.144212353328214e-06
Z:  [0.000123 0.000129 0.000135 0.000141]
--------------------------------------
S:  6.144212353328214e-06
Z:  [0.000147 0.000154 0.00016  0.000166]
--------------------------------------
S:  6.144212353328214e-06
Z:  [0.000172 0.000178 0.000184 0.00019 ]
--------------------------------------


In [23]:
Zsum=np.zeros((H), dtype=float)

for i in range(W*2):
    Zsum+=Z[i]

print("Zsum: ",Zsum)

Zsum:  [0.000688 0.000737 0.000786 0.000836]
