In [4]:
import numpy as np

W = 4
H = 4

Q = np.zeros((W*2, H), dtype=float)
K = np.zeros((W*2, H), dtype=float)
V = np.zeros((W*2, int(H/2)), dtype=float)

for i in range(W*2):
    for j in range(H):
        Q[i, j] = i*H + j + 1
        K[i, j] = i*H + j + 2
        if(j%2): V[i, int(j/2)] = i*H + j

print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

Q:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]
K:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]
 [26. 27. 28. 29.]
 [30. 31. 32. 33.]]
V:
 [[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]
 [13. 15.]
 [17. 19.]
 [21. 23.]
 [25. 27.]
 [29. 31.]]


In [5]:
import math

def Attention_Core(Q, K, V, scale=3):
    diff=abs(np.sum(Q-K))
    S=math.e**(-scale*diff)

    print("S: ",S)

    Z=S*V
    print("Z: ",Z)
    print("--------------------------------------")

    return np.array(S,dtype=float),np.array(Z,dtype=float)


In [6]:
S = np.zeros((W*2), dtype=float)
Z = np.zeros((W*2, H), dtype=float)

for i in range(W*2):
    S[i],Z[i]=Attention_Core(Q[0], K[i], V[i])

S:  6.144212353328214e-06
Z:  [6.14421235e-06 1.84326371e-05]
--------------------------------------


ValueError: could not broadcast input array from shape (2,) into shape (4,)

In [ ]:
Zsum=np.zeros((H), dtype=float)
sSum=np.sum(S)
print("sSum: ",sSum)

for i in range(W*2):
    Zsum+=Z[i]

print("Zsum: ",Zsum)

print("Final Output: ",Zsum/sSum)

sSum:  6.144212353328214e-06
Zsum:  [3.502604e-26 6.144212e-06 1.228842e-05 1.843264e-05]
Final Output:  [5.700656e-21 1.000000e+00 2.000000e+00 3.000000e+00]
