In [18]:
import numpy as np

W = 4
H = 4

Q = np.zeros((W*2, H), dtype=float)
K = np.zeros((W*2, H), dtype=float)
V = np.zeros((W*2, int(H/2)), dtype=float)

for i in range(W*2):
    for j in range(H):
        Q[i, j] = i*H + j + 1
        K[i, j] = i*H + j + 2
        if(j%2): V[i, int(j/2)] = i*H + j

print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

Q:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]
K:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]
 [26. 27. 28. 29.]
 [30. 31. 32. 33.]]
V:
 [[ 1.  3.]
 [ 5.  7.]
 [ 9. 11.]
 [13. 15.]
 [17. 19.]
 [21. 23.]
 [25. 27.]
 [29. 31.]]


In [19]:
import math

def Attention_Core(Q, K, V, scale=3):
    diff=abs(np.sum(Q-K))
    S=math.e**(-scale*diff)

    print("S: ",S)

    Z=S*V
    print("Z: ",Z)
    print("--------------------------------------")

    return np.array(S,dtype=float),np.array(Z,dtype=float)


In [20]:
S = np.zeros((W*2), dtype=float)
Z = np.zeros((W*2, int(H/2)), dtype=float)

for i in range(W*2):
    S[i],Z[i]=Attention_Core(Q[0], K[i], V[i])

S:  6.144212353328214e-06
Z:  [6.14421235e-06 1.84326371e-05]
--------------------------------------
S:  8.756510762696549e-27
Z:  [4.37825538e-26 6.12955753e-26]
--------------------------------------
S:  1.2479464629129583e-47
Z:  [1.12315182e-46 1.37274111e-46]
--------------------------------------
S:  1.7785284761271454e-68
Z:  [2.31208702e-67 2.66779271e-67]
--------------------------------------
S:  2.5346949043083827e-89
Z:  [4.30898134e-88 4.81592032e-88]
--------------------------------------
S:  3.612356138326788e-110
Z:  [7.58594789e-109 8.30841912e-109]
--------------------------------------
S:  5.148200222412096e-131
Z:  [1.28705006e-129 1.39001406e-129]
--------------------------------------
S:  7.337030047740632e-152
Z:  [2.12773871e-150 2.27447931e-150]
--------------------------------------


In [21]:
Zsum=np.zeros(int(H/2), dtype=float)
sSum=np.sum(S)
print("sSum: ",sSum)

for i in range(W*2):
    Zsum+=Z[i]

print("Zsum: ",Zsum)

print("Final Output: ",Zsum/sSum)

sSum:  6.144212353328214e-06
Zsum:  [6.14421235e-06 1.84326371e-05]
Final Output:  [1. 3.]
