In [32]:
import numpy as np

W = 4
H = 4

Q = np.zeros((W*2, H), dtype=float)
K = np.zeros((W*2, H), dtype=float)
V = np.zeros((W*2, H), dtype=float)

for i in range(W*2):
    for j in range(H):
        Q[i, j] = i*H + j + 1
        K[i, j] = i*H + j + 2
        V[i, j] = i*H + j

print("Q:\n", Q)
print("K:\n", K)
print("V:\n", V)

Q:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]]
K:
 [[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]
 [22. 23. 24. 25.]
 [26. 27. 28. 29.]
 [30. 31. 32. 33.]]
V:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]
 [24. 25. 26. 27.]
 [28. 29. 30. 31.]]


In [33]:
import math

def Attention_Core(Q, K, V, scale=3):
    diff=abs(np.sum(Q-K))
    S=math.e**(-scale*diff)

    print("S: ",S)

    Z=S*V
    print("Z: ",Z)
    print("--------------------------------------")

    return np.array(S,dtype=float),np.array(Z,dtype=float)


In [34]:
S = np.zeros((W*2), dtype=float)
Z = np.zeros((W*2, H), dtype=float)

for i in range(W*2):
    S[i],Z[i]=Attention_Core(Q[0], K[i], V[i])

S:  6.144212353328214e-06
Z:  [0.000000e+00 6.144212e-06 1.228842e-05 1.843264e-05]
--------------------------------------
S:  8.756510762696549e-27
Z:  [3.502604e-26 4.378255e-26 5.253906e-26 6.129558e-26]
--------------------------------------
S:  1.2479464629129583e-47
Z:  [9.983572e-47 1.123152e-46 1.247946e-46 1.372741e-46]
--------------------------------------
S:  1.7785284761271454e-68
Z:  [2.134234e-67 2.312087e-67 2.489940e-67 2.667793e-67]
--------------------------------------
S:  2.5346949043083827e-89
Z:  [4.055512e-88 4.308981e-88 4.562451e-88 4.815920e-88]
--------------------------------------
S:  3.612356138326788e-110
Z:  [7.224712e-109 7.585948e-109 7.947184e-109 8.308419e-109]
--------------------------------------
S:  5.148200222412096e-131
Z:  [1.235568e-129 1.287050e-129 1.338532e-129 1.390014e-129]
--------------------------------------
S:  7.337030047740632e-152
Z:  [2.054368e-150 2.127739e-150 2.201109e-150 2.274479e-150]
-------------------------------------

In [35]:
Zsum=np.zeros((H), dtype=float)
sSum=np.sum(S)
print("sSum: ",sSum)

for i in range(W*2):
    Zsum+=Z[i]

print("Zsum: ",Zsum)

print("Final Output: ",Zsum/sSum)

sSum:  6.144212353328214e-06
Zsum:  [3.502604e-26 6.144212e-06 1.228842e-05 1.843264e-05]
Final Output:  [5.700656e-21 1.000000e+00 2.000000e+00 3.000000e+00]
